[package]
name = "inceptionv3"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
flate2 = "*"
image = "*"
ndarray = "*"
mio_httpc = "*"
tar = "*"
tract-core = { path = "../../core" }
tract-tensorflow = { path = ".." }

[dev-dependencies]
dinghy-test = "*"
